---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-net-openstack-org-v1beta1-openstacknet
  failurePolicy: Fail
  name: mopenstacknet.kb.io
  rules:
  - apiGroups:
    - net.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - openstacknets
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-net-openstack-org-v1beta1-openstacknetattachment
  failurePolicy: Fail
  name: mopenstacknetattachment.kb.io
  rules:
  - apiGroups:
    - net.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - openstacknetattachments
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-net-openstack-org-v1beta1-openstacknetconfig
  failurePolicy: Fail
  name: mopenstacknetconfig.kb.io
  rules:
  - apiGroups:
    - net.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - openstacknetconfigs
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-net-openstack-org-v1beta1-openstacknet
  failurePolicy: Fail
  name: vopenstacknet.kb.io
  rules:
  - apiGroups:
    - net.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - openstacknets
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-net-openstack-org-v1beta1-openstacknetattachment
  failurePolicy: Fail
  name: vopenstacknetattachment.kb.io
  rules:
  - apiGroups:
    - net.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - openstacknetattachments
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-net-openstack-org-v1beta1-openstacknetconfig
  failurePolicy: Fail
  name: vopenstacknetconfig.kb.io
  rules:
  - apiGroups:
    - net.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - openstacknetconfigs
  sideEffects: None
