# permissions for end users to view openstacknetconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openstacknetconfig-viewer-role
rules:
- apiGroups:
  - net.openstack.org
  resources:
  - openstacknetconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - net.openstack.org
  resources:
  - openstacknetconfigs/status
  verbs:
  - get
