# permissions for end users to edit openstacknets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openstacknet-editor-role
rules:
- apiGroups:
  - net.openstack.org
  resources:
  - openstacknets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - net.openstack.org
  resources:
  - openstacknets/status
  verbs:
  - get
