---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - cinder.openstack.org
  resources:
  - cinders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.openstack.org
  resources:
  - openstackcontrolplanes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.openstack.org
  resources:
  - openstackcontrolplanes/finalizers
  verbs:
  - update
- apiGroups:
  - core.openstack.org
  resources:
  - openstackcontrolplanes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - glance.openstack.org
  resources:
  - glances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.cni.cncf.io
  resources:
  - network-attachment-definitions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - keystone.openstack.org
  resources:
  - keystoneapis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mariadb.openstack.org
  resources:
  - mariadbs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - net.openstack.org
  resources:
  - openstacknetattachments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - net.openstack.org
  resources:
  - openstacknetattachments/finalizers
  verbs:
  - update
- apiGroups:
  - net.openstack.org
  resources:
  - openstacknetattachments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - net.openstack.org
  resources:
  - openstacknets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - net.openstack.org
  resources:
  - openstacknets/finalizers
  verbs:
  - update
- apiGroups:
  - net.openstack.org
  resources:
  - openstacknets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - nmstate.io
  resources:
  - nodenetworkconfigurationenactments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nmstate.io
  resources:
  - nodenetworkconfigurationpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - placement.openstack.org
  resources:
  - placementapis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rabbitmq.com
  resources:
  - rabbitmqclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rabbitmq.openstack.org
  resources:
  - transporturls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rabbitmq.openstack.org
  resources:
  - transporturls/finalizers
  verbs:
  - update
- apiGroups:
  - rabbitmq.openstack.org
  resources:
  - transporturls/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sriovnetwork.openshift.io
  resources:
  - sriovnetworknodepolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sriovnetwork.openshift.io
  resources:
  - sriovnetworks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
